# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biodiversidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(blank=True, max_length=200, null=True)),
                ('algorithm', models.CharField(blank=True, max_length=200, null=True)),
                ('database', models.CharField(blank=True, max_length=200, null=True)),
                ('qseqid', models.CharField(blank=True, max_length=200, null=True)),
                ('sseqid', models.CharField(blank=True, max_length=200, null=True)),
                ('pident', models.CharField(blank=True, max_length=200, null=True)),
                ('length', models.CharField(blank=True, max_length=200, null=True)),
                ('mismatch', models.CharField(blank=True, max_length=200, null=True)),
                ('gapopen', models.CharField(blank=True, max_length=200, null=True)),
                ('qstart', models.CharField(blank=True, max_length=200, null=True)),
                ('qend', models.CharField(blank=True, max_length=200, null=True)),
                ('sstart', models.CharField(blank=True, max_length=200, null=True)),
                ('send', models.CharField(blank=True, max_length=200, null=True)),
                ('evalue', models.CharField(blank=True, max_length=200, null=True)),
                ('bitscore', models.CharField(blank=True, max_length=200, null=True)),
                ('gi', models.CharField(blank=True, max_length=200, null=True)),
                ('geneid', models.CharField(blank=True, max_length=200, null=True)),
                ('ncbitaxon', models.CharField(blank=True, max_length=200, null=True)),
                ('ltaxon', models.CharField(blank=True, max_length=200, null=True)),
                ('repid', models.CharField(blank=True, max_length=200, null=True)),
                ('clustername', models.CharField(blank=True, max_length=200, null=True)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
