# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listagens', '0002_auto_20170403_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodiversidade',
            name='gi',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
