# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listagens', '0003_auto_20170403_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodiversidade',
            name='clustername',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='biodiversidade',
            name='gi',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
