# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-30 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listagens', '0004_auto_20170403_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodiversidade',
            name='frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biodiversidade',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biodiversidade',
            name='lat2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biodiversidade',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biodiversidade',
            name='long2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biodiversidade',
            name='original_seq_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversidade',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversidade',
            name='station',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversidade',
            name='string1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversidade',
            name='string2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversidade',
            name='string3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversidade',
            name='string4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='biodiversidade',
            name='algorithm',
            field=models.CharField(blank=True, help_text='algorithm', max_length=200, null=True, verbose_name='Algorithm'),
        ),
        migrations.AlterField(
            model_name='biodiversidade',
            name='bitscore',
            field=models.CharField(blank=True, help_text='bitscore', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='biodiversidade',
            name='clustername',
            field=models.CharField(blank=True, help_text='clustername', max_length=500, null=True, verbose_name='Cluster Name'),
        ),
        migrations.AlterField(
            model_name='biodiversidade',
            name='database',
            field=models.CharField(blank=True, help_text='database', max_length=200, null=True, verbose_name='Database'),
        ),
        migrations.AlterField(
            model_name='biodiversidade',
            name='evalue',
            field=models.CharField(blank=True, help_text='evalue', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='biodiversidade',
            name='gapopen',
            field=models.CharField(blank=True, help_text='gapopen', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='biodiversidade',
            name='geneid',
            field=models.CharField(blank=True, help_text='geneid', max_length=200, null=True, verbose_name='GeneID'),
        ),
        migrations.AlterField(
            model_name='biodiversidade',
            name='gi',
            field=models.CharField(blank=True, help_text='gi', max_length=5000, null=True, verbose_name='GI'),
        ),
        migrations.AlterField(
            model_name='biodiversidade',
            name='length',
            field=models.CharField(blank=True, help_text='length', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='biodiversidade',
            name='ltaxon',
            field=models.CharField(blank=True, help_text='ltaxon', max_length=200, null=True, verbose_name='Lowest taxon of the cluster'),
        ),
        migrations.AlterField(
            model_name='biodiversidade',
            name='mismatch',
            field=models.CharField(blank=True, help_text='mismatch', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='biodiversidade',
            name='ncbitaxon',
            field=models.CharField(blank=True, help_text='ncbitaxon', max_length=200, null=True, verbose_name='NCBI-taxon'),
        ),
        migrations.AlterField(
            model_name='biodiversidade',
            name='obs',
            field=models.CharField(blank=True, help_text='obs', max_length=1000, null=True, verbose_name='Obs'),
        ),
        migrations.AlterField(
            model_name='biodiversidade',
            name='pident',
            field=models.CharField(blank=True, help_text='pident', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='biodiversidade',
            name='qend',
            field=models.CharField(blank=True, help_text='qend', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='biodiversidade',
            name='qseqid',
            field=models.CharField(blank=True, help_text='qseqid', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='biodiversidade',
            name='qstart',
            field=models.CharField(blank=True, help_text='qstart', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='biodiversidade',
            name='repid',
            field=models.CharField(blank=True, help_text='repid', max_length=200, null=True, verbose_name='RepID'),
        ),
        migrations.AlterField(
            model_name='biodiversidade',
            name='send',
            field=models.CharField(blank=True, help_text='send', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='biodiversidade',
            name='species',
            field=models.CharField(blank=True, help_text='species', max_length=200, null=True, verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='biodiversidade',
            name='sseqid',
            field=models.CharField(blank=True, help_text='sseqid', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='biodiversidade',
            name='sstart',
            field=models.CharField(blank=True, help_text='sstart', max_length=200, null=True),
        ),
    ]
