# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-30 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listagens', '0005_auto_20180530_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('profundidade', models.TextField(blank=True, null=True)),
                ('hshannon', models.FloatField(blank=True, null=True)),
                ('parametro_2', models.FloatField(blank=True, null=True)),
                ('parametro_3', models.FloatField(blank=True, null=True)),
                ('parametro_4', models.FloatField(blank=True, null=True)),
                ('parametro_5', models.FloatField(blank=True, null=True)),
                ('parametro_6', models.FloatField(blank=True, null=True)),
                ('parametro_7', models.FloatField(blank=True, null=True)),
                ('parametro_8', models.FloatField(blank=True, null=True)),
                ('parametro_9', models.FloatField(blank=True, null=True)),
                ('parametro_10', models.FloatField(blank=True, null=True)),
                ('parametro_11', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('classificacao', models.TextField(blank=True, null=True)),
                ('fonte', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estacoes',
                'managed': False,
            },
        ),
    ]
