# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-26 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listagens', '0006_estacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_names', models.TextField(blank=True, db_column='row.names', null=True)),
                ('cod', models.FloatField(blank=True, db_column='COD', null=True)),
                ('item_taxonomico', models.NullBooleanField(db_column='Item Taxonomico')),
                ('código_item_taxonomico', models.NullBooleanField(db_column='Código Item Taxonomico')),
                ('item_taxonomico_superior', models.NullBooleanField(db_column='Item Taxonomico Superior')),
                ('codigo_item_taxononico_superior', models.NullBooleanField(db_column='Codigo Item Taxononico Superior')),
                ('nome_atribuido', models.TextField(blank=True, db_column='Nome Atribuido', null=True)),
                ('filo', models.TextField(blank=True, db_column='Filo', null=True)),
                ('classe', models.TextField(blank=True, db_column='Classe', null=True)),
                ('ordem', models.TextField(blank=True, db_column='Ordem', null=True)),
                ('familia', models.TextField(blank=True, db_column='Familia', null=True)),
                ('genero', models.NullBooleanField(db_column='Genero')),
                ('especie', models.TextField(blank=True, db_column='Especie', null=True)),
                ('fonte', models.TextField(blank=True, db_column='Fonte', null=True)),
                ('amostras', models.TextField(blank=True, db_column='Amostras', null=True)),
                ('taxonid', models.TextField(blank=True, db_column='TaxonID', null=True)),
                ('rank', models.TextField(blank=True, db_column='Rank', null=True)),
                ('species', models.TextField(blank=True, null=True)),
                ('genus', models.TextField(blank=True, null=True)),
                ('family', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'especies',
                'managed': False,
            },
        ),
    ]
