# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-27 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Identificador único de uma amostra. Deverá seguir uma taxonomia definida posteriormente', max_length=50)),
                ('data_da_coleta', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('altitude', models.IntegerField()),
                ('solo', models.CharField(max_length=200)),
                ('vegetacao', models.CharField(max_length=200, verbose_name='Vegetação')),
                ('altura', models.FloatField()),
                ('diametro', models.FloatField(verbose_name='Diâmetro')),
                ('notas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClasseQuimica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Eluente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('polar', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('common', models.CharField(help_text='Nome popular desta espécie de planta, ex.: pitangueira', max_length=200)),
            ],
            options={
                'verbose_name': 'Espécie',
            },
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Família',
            },
        ),
        migrations.CreateModel(
            name='Fracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eluente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobureau.Eluente')),
                ('extrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobureau.Extrato')),
            ],
        ),
        migrations.CreateModel(
            name='Fracionamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positivo', models.BooleanField()),
                ('classe_quimica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobureau.ClasseQuimica')),
                ('fracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobureau.Fracao')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobureau.Familia')),
            ],
            options={
                'verbose_name': 'Gênero',
            },
        ),
        migrations.CreateModel(
            name='OrgaoDePlanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao', models.CharField(max_length=100, verbose_name='Órgão')),
            ],
            options={
                'verbose_name': 'Órgão de Planta',
            },
        ),
        migrations.CreateModel(
            name='ParteDePlanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=50)),
                ('cheiro', models.CharField(max_length=50)),
                ('peso', models.FloatField()),
                ('notas', models.TextField()),
                ('amostra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobureau.Amostra')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobureau.OrgaoDePlanta')),
            ],
        ),
        migrations.CreateModel(
            name='Sequenciamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Sequenciamento Genético')),
                ('arquivo_fasta', models.CharField(max_length=1000)),
                ('extrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobureau.Extrato')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeExtrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='extrato',
            name='parte_de_planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobureau.ParteDePlanta'),
        ),
        migrations.AddField(
            model_name='extrato',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobureau.TipoDeExtrato'),
        ),
        migrations.AddField(
            model_name='especie',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobureau.Genero'),
        ),
        migrations.AddField(
            model_name='amostra',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobureau.Especie'),
        ),
    ]
