# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-28 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('biobureau', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amostra',
            name='identificador',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
