# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-25 16:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobureau', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especime',
            name='abund',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='especime',
            name='autor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='especime',
            name='data_erva',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='especime',
            name='etnologico',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='especime',
            name='identid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='especime',
            name='light',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='especime',
            name='nome_comum',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='especime',
            name='nome_erva',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='especime',
            name='numero_individuos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='especime',
            name='photonum',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
