# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-25 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobureau', '0002_auto_20180825_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='especime',
            name='ponto_de_referencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
