# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-28 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobureau', '0002_auto_20180728_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='common',
            field=models.CharField(blank=True, help_text='Nome popular desta espécie de planta, ex.: pitangueira', max_length=200, null=True),
        ),
    ]
