# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-28 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobureau', '0003_auto_20180728_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amostra',
            name='altitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='data_da_coleta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='diametro',
            field=models.FloatField(blank=True, null=True, verbose_name='Diâmetro'),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='solo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='vegetacao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Vegetação'),
        ),
    ]
