# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-25 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobureau', '0003_especime_ponto_de_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='fracionamento',
            name='protocolo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
