# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-26 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biobureau', '0004_fracionamento_protocolo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosTLC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(blank=True, null=True)),
                ('linha', models.IntegerField(blank=True, null=True)),
                ('coluna', models.IntegerField(blank=True, null=True)),
                ('resultado', models.BooleanField(default=False)),
                ('tipo_composto_tlc', models.IntegerField(blank=True, null=True)),
                ('classe_quimica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobureau.ClasseQuimica')),
            ],
            options={
                'verbose_name': 'Dados TLC',
                'verbose_name_plural': 'Dados TLC',
            },
        ),
        migrations.RemoveField(
            model_name='composto',
            name='classe_quimica',
        ),
        migrations.RemoveField(
            model_name='composto',
            name='positivo',
        ),
        migrations.RemoveField(
            model_name='fracao',
            name='eluente',
        ),
        migrations.AddField(
            model_name='composto',
            name='data_isolamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='composto',
            name='depid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='composto',
            name='smiles',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fracao',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fracao',
            name='numero_fracao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fracao',
            name='rt_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fracao',
            name='rt_inicial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadostlc',
            name='fracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobureau.Fracao'),
        ),
    ]
