# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-26 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biobureau', '0005_auto_20180826_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacaTLC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_faixas', models.IntegerField(blank=True, null=True)),
                ('data_da_analise', models.DateField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='')),
                ('notas', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='eluente',
            name='polar',
        ),
        migrations.AddField(
            model_name='eluente',
            name='classe',
            field=models.CharField(default='Polar', max_length=100),
        ),
        migrations.AddField(
            model_name='eluente',
            name='composicao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='placatlc',
            name='eluente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobureau.Eluente'),
        ),
        migrations.AddField(
            model_name='dadostlc',
            name='placa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='biobureau.PlacaTLC'),
            preserve_default=False,
        ),
    ]
