# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-27 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biobureau', '0007_placatlc_idextracta'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadostlc',
            name='fracionamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biobureau.Fracionamento'),
        ),
        migrations.AlterField(
            model_name='dadostlc',
            name='fracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biobureau.Fracao'),
        ),
    ]
