# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-27 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biobureau', '0008_auto_20180827_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placatlc',
            name='eluente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biobureau.Eluente'),
        ),
    ]
