# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-27 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biobureau', '0009_auto_20180827_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadostlc',
            name='classe_quimica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biobureau.ClasseQuimica'),
        ),
        migrations.AlterField(
            model_name='dadostlc',
            name='resultado',
            field=models.NullBooleanField(default=False),
        ),
    ]
