# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-27 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobureau', '0010_auto_20180827_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especime',
            name='etnologico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
