# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-16 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biobureau', '0011_auto_20180827_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algoritmo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GeneInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneOntology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qseqid', models.CharField(blank=True, help_text='qseqid', max_length=200, null=True)),
                ('sseqid', models.CharField(blank=True, help_text='sseqid', max_length=200, null=True)),
                ('pident', models.CharField(blank=True, help_text='pident', max_length=200, null=True)),
                ('length', models.CharField(blank=True, help_text='length', max_length=200, null=True)),
                ('mismatch', models.CharField(blank=True, help_text='mismatch', max_length=200, null=True)),
                ('gapopen', models.CharField(blank=True, help_text='gapopen', max_length=200, null=True)),
                ('qstart', models.CharField(blank=True, help_text='qstart', max_length=200, null=True)),
                ('qend', models.CharField(blank=True, help_text='qend', max_length=200, null=True)),
                ('sstart', models.CharField(blank=True, help_text='sstart', max_length=200, null=True)),
                ('send', models.CharField(blank=True, help_text='send', max_length=200, null=True)),
                ('evalue', models.CharField(blank=True, help_text='evalue', max_length=200, null=True)),
                ('bitscore', models.CharField(blank=True, help_text='bitscore', max_length=200, null=True)),
                ('geneid', models.CharField(blank=True, help_text='geneid', max_length=200, null=True, verbose_name='GeneID')),
                ('ncbitaxon', models.CharField(blank=True, help_text='ncbitaxon', max_length=200, null=True, verbose_name='NCBI-taxon')),
                ('ltaxon', models.CharField(blank=True, help_text='ltaxon', max_length=200, null=True, verbose_name='Lowest taxon of the cluster')),
                ('repid', models.CharField(blank=True, help_text='repid', max_length=200, null=True, verbose_name='RepID')),
                ('clustername', models.CharField(blank=True, help_text='clustername', max_length=500, null=True, verbose_name='Cluster Name')),
                ('station', models.CharField(blank=True, max_length=255, null=True)),
                ('geneinfo', models.ManyToManyField(to='biobureau.GeneInfo')),
                ('geneontology', models.ManyToManyField(to='biobureau.GeneOntology')),
                ('sequenciamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobureau.Sequenciamento')),
            ],
        ),
        migrations.AddField(
            model_name='sequenciamento',
            name='algoritmo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biobureau.Algoritmo'),
        ),
        migrations.AddField(
            model_name='sequenciamento',
            name='database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biobureau.Database'),
        ),
    ]
