# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-17 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobureau', '0012_auto_20180916_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequenciamento',
            name='arquivo_fasta',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
