# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-02 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biobureau', '0013_auto_20180917_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='FonteFamilia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Fonte de Família',
                'verbose_name_plural': 'Fontes de Família',
            },
        ),
        migrations.AddField(
            model_name='familia',
            name='fonte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biobureau.FonteFamilia'),
        ),
    ]
