# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-02 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobureau', '0014_auto_20181102_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='fonte',
        ),
        migrations.AddField(
            model_name='familia',
            name='fonte',
            field=models.ManyToManyField(to='biobureau.FonteFamilia'),
        ),
    ]
