# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-06 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobureau', '0016_auto_20181106_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fontefamilia',
            name='brasileira',
        ),
        migrations.RemoveField(
            model_name='fontefamilia',
            name='taxid',
        ),
        migrations.AddField(
            model_name='familia',
            name='brasileira',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familia',
            name='taxid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
