# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-07 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biobureau', '0017_auto_20181106_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoFasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_fasta', models.CharField(blank=True, max_length=1000, null=True)),
                ('sequenciamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobureau.Sequenciamento')),
            ],
        ),
    ]
