# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-09 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobureau', '0018_arquivofasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneontology',
            name='descricao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
